workdir: "WORKDIR"

oligo_info: "oligo_info.tsv"

amplicon_dir: '00.amplicon'
fastq_dir: '00.fastq'
clean_dir: '01.clean'
amplicon_align_dir: '02.amplicon_align'
barcode_dir: '03.barcode'
oligo_coverage_dir: '04.oligo_coverage'
visualize_dir: '05.visualize'